#! /bin/sh 
# /etc/init.d/RFID 

### BEGIN INIT INFO 
# Provides:          RFID 
# Required-Start:       $local_fs $remote_fs $network $time 
# Required-Stop:        $local_fs $remote_fs $network $time 
# Default-Start:        2 3 4 5   
# Default-Stop:         0 1 6 
# Should-Start:         postgresql 
# Should-Stop:          postgresql 
# Short-Description: Simple script to start a program at boot 
# Description:       A simple script from www.stuffaboutcode.com which will sta$ 
### END INIT INFO 

case "$1" in 
  start) 
   echo "Starting RFID" 
    cd /home/pi/Desktop/RFID-US/
    /usr/bin/python3.2 /home/pi/Desktop/RFID-US/main.py >> /home/pi/Desktop/RFID-US/salida.txt & 
  ;; 
  stop) 
    echo "Stopping RFID" 
    killall python3.2 
    ;; 
  *) 
    echo "Usage: /etc/init.d/RFID {start|stop}" 
    exit 1 

    ;; 
esac 
